apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80   # By default the targetPort will be set to the same value as the port field. It's optional here.
  selector:            # The label selector (i.e. the spec.selector) is used by the Service to target the backend pods
    app: nginx         # Make sure to match the Pod labels
    tier: frontend

  type: LoadBalancer   # ClusterIP is the default service type, which is cluster internal only
                       # If you set the service type to LoadBalancer, AWS will provision an ELB and expose the service to the Internet
